### ISSUE TITLE
Must be authenticated as user with page creation permissions

### ISSUE THREAD

**Issue by theopaolo** [mogelbrod/kirby-copy-files#3]
Hi, first thx for this more than needed option, hope someday it will be part of Kirby.
I'm just trying out the widget and when copying a page it get this message : 

**"Must be authenticated as user with page creation permissions"** 

_I'm on the admin account._

Maybe i'm doing something wrong, 
Thanks in advance for your help.

**Comment by mogelbrod** [comment]
Which Kirby version are you using, v2.4? I've yet to try the plugin with it and imagine that the user role changes might have broken this plugin. Will look into it.

**Comment by mogelbrod** [comment]
Should be fixed by PR #5.
